<?php
/* @var $this VirtualPiggy_VirtualPiggy_Block_Checkout_ParentConfirmation_ChildrenSelector */
$childrens = $this->getChildrens();
?>




<li class="section allow active" id="opc-billing">
    <div class="step-title">
        <h2><?php echo $this->__("Child information") ?></h2>
    </div>

    <div id="checkout-step-billing" class="step a-item" style="">
        <fieldset>
            <ul class="form-list">
                <li id="billing-new-address-form">
                    <fieldset>
                        <ul>
                            <li class="fields">
                                <div class="field">
                                    <label for="children" class="required">This transaction is for</label>
                                    <div class="input-box">
                                        <select name="children" id="childSelector" class="required-entry">
                                            <option value="" ></option>
                                            <?php foreach ($childrens as $key => $children): ?>
                                                <option value="<?php echo $children->getChildrenIdentifier() ?>"><?php echo $children->getName() ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                </li>
                <li class="control">
                    <!--input type="checkbox" id="notifyChild" name="notifyChild" value="1" /><label for="notifyChild" ><?php echo $this->__("Notify the child about this transaction") ?></label><br-->
                    <input type="checkbox" id="deliverToChildAddress" name="deliverToChildAddress" value="1" />
                    <label for="deliverToChildAddress" ><?php echo $this->__("Deliver to the child's address") ?></label>
                </li>
            </ul>

        </fieldset>
    </div>
</li>