<?php /* @var $this VirtualPiggy_VirtualPiggy_Block_Payment_Form_VirtualPiggy */ ?>
<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <label><?php echo $this->__('Make Check payable to:') ?></label>
            <?php echo $this->escapeHtml($this->getMethod()->getPayableTo()) ?>
        </li>
        <?php endif; ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <label><?php echo Mage::helper('payment')->__('Send Check to:') ?></label>
            <address class="checkmo-mailing-address">
                <?php echo nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
            </address>
        </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>
