<?php /* @var $this VirtualPiggy_VirtualPiggy_Block_Checkout_Button */ ?>

<script type="text/javascript">
  // 1. create "oinkRadio" element
  // 2. save onepage-guest-register-button onclick method (prevents overiding core)
  // 3. create vpCheckout method
  // 4. only add Oink "radio" and replace "onepage" button (#2) if guest_checkout enabled.
  // 5. in checkoutVP call onepage onclick method if Oink Radio not selected
  // 6. use admin (config) for Oink image ->  	
  	
	// 1. Oink Radio Button
  	var oinkRadio = '<li><input type="radio" name="checkout_method" id="lologin:virtualpiggy" value="virtualpiggy" class="radio"> <label for="login:virtualpiggy"><img src="https://cdn.virtualpiggy.com/public/images/checkout-168x20.png" height="12px" style="vertical-align:middle;" /></label>';
  
	// 2. Save "Onepage Checkout(Magento)" onclick "function"	
	var onepageclick = $('onepage-guest-register-button').onclick;
  	 
	// 3. Create Oink onclick "funtion"  	 
	var vpContinue = '<button id="onepage-guest-register-button" type="button" class="button" onclick="checkoutVP();"><span><span>Continue</span></span></button>';

	// 4. If "Allow Guest Checkout" enabled, add Oink "radio" select and replace "onepage" guest with "oink" 	 
	
 	<?php
 	
 		$config = Mage::getStoreConfig('checkout/options');
		$oinkCheckout = Mage::getStoreConfig("virtualpiggy/checkoutbutton/oink_radio");
						//	echo "button: ".$oinkCheckout;
		
		if ($config['guest_checkout']) {
			if ($oinkCheckout == '0' || $oinkCheckout == '2' ) {
				// Merchant selected (0) "Checkout Button and Radio Select" OR
				// Merchant selected (2) "Checkout Button Only"
 	?>
				$('login:register').insert({
					before: oinkRadio
				});
				$('onepage-guest-register-button').replace(vpContinue);
		<?php
			}
		}
     ?>
     
function checkoutVP() {
	
	// 5. if Oink Radio selected display Oink Login else call "Onepage Checkout (Magento)"
	
	if(document.getElementById('lologin:virtualpiggy').checked) {
		virtualPiggyLoginForm.toggleTooltip();
	}
	else {
		onepageclick();
	}
	
}	
	
</script>
<?php
		if ($oinkCheckout == '0' || $oinkCheckout == '1' ) { ?>

			<a href="<?php echo $this->getCheckoutUrl() ?>" id="virtual-piggy-checkout-button" onclick="return virtualPiggyLoginForm.toggleTooltip()" class="<?php echo $this->getCssClass() ?>"><img src="https://cdn.virtualpiggy.com/public/images/checkout-145x42.png" /></a>
<?php 	} ?>	