<style>
    h1.page-title{
        color:#1484c5;
        text-decoration: underline;
    }
    #virtualPiggyParentConfirmation select{
        margin-left:10px;
    }
    #virtualPiggyParentConfirmation{
        font-size: 14px;
    }
    #paymentAccounts{
        width:360px;
        margin-bottom:15px;
    }
    #paymentAccounts th{
        color:#fff;
        font-weight: bold;
        background-color: #1484c5;
    }
    #paymentAccounts td{
        border:1px solid #676;
        padding:5px;
    }
</style>
<div class="page-title">
    <h1><?php echo $this->__('Virtual Piggy Guest Checkout'); ?></h1>
</div>
<ol class="opc">
    <form method="POST" action="<?php echo $this->getFormActionUrl() ?>" id="virtualPiggyParentConfirmation" >
        <?php echo $this->getChildHtml("childrenSelector") ?>
        <?php echo $this->getChildHtml("payment") ?>
        
        <div class="buttons-set" id="billing-buttons-container">
            <button type="submit" title="<?php echo $this->__('Finalize the Transaction'); ?>" class="button" ><span><span><?php echo $this->__('Finalize the Transaction') ?></span></span></button>
        </div>        
        
    </form>
</ol>
<script type="text/javascript" >
//<![CDATA[
    var virtualPiggyParentConfirmation = new VarienForm('virtualPiggyParentConfirmation', true);
//]]>
</script>